name: CI/CD
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "book.toml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.BE_RUSTACEAN_KEY }}
          external_repository: Daiki48/be-rustacean
          publish_branch: main
          publish_dir: ./book
